{% set name = "types-Deprecated" %}
{% set version = "1.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Deprecated-{{ version }}.tar.gz
  sha256: 5e701f4b2d1e1928795fe21e92c39951fd0bb4d716fd5306d0548553522ba5a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/deprecated-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Deprecated
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
